-- MySQL Script generated by MySQL Workbench
-- Mon Jan 14 17:47:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema marusei
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `marusei` ;

-- -----------------------------------------------------
-- Schema marusei
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marusei` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ;
SHOW WARNINGS;
USE `marusei` ;

-- -----------------------------------------------------
-- Table `marusei`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marusei`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `nickname` VARCHAR(15) NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `modified_ts` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_ACCOUNT_EMAIL` (`email` ASC),
  UNIQUE INDEX `UQ_ACCOUNT_NICKNAME` (`nickname` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `marusei`.`credential`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marusei`.`credential` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `account` INT UNSIGNED NOT NULL,
  `public_key` VARCHAR(128) NOT NULL,
  `secret_hash` VARCHAR(255) NOT NULL,
  `created_at` BIGINT NOT NULL,
  `updated_at` BIGINT NOT NULL,
  `modified_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `FK_CREDENTIAL_PK_ACCOUNT` (`account` ASC),
  UNIQUE INDEX `UQ_CREDENTIAL_PUBLIC_KEY` (`public_key` ASC),
  CONSTRAINT `FK_CREDENTIAL_PK_ACCOUNT`
    FOREIGN KEY (`account`)
    REFERENCES `marusei`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
